services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - client/.env.dev
    networks:
      - app-network
  
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - server/.env.dev
    networks:
      - app-network

  database:
    image: mysql:latest
    restart: always
    env_file:
      - server/.env.dev
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./speech_scape.sql:/docker-entrypoint-initdb.d/speech_scape.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      timeout: 5s

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge